### ISSUE TITLE
Issue using MariaDB database

### ISSUE THREAD

**Issue by spfaffly** [lando/acquia#100]
I saw there was work done recently to add MariaDB. I tried adding `database: mariadb` in the `config:` portion in my .lando.yml file and it looked like it didn't take - it would still install MySQL.

The only way I could get MariaDB to install would be to specify it under the services:

```
database: 
      type: mariadb
```

And to my understanding this isn't the proper way - but I could be wrong. Any help would be appreciated. Thanks!

**Comment by reynoldsalec** [comment]
@spfaffly Mariadb isn't a configuration option of Acquia, but you've made a good point. A lot of the recipes had an undocumented ability to change their `database` option to something other than a documented value, hence why we kept adding MariadB functionality to them.

The Acquia recipe is actually hardcoded to `mysql:5.7`: https://github.com/lando/acquia/blob/main/builders/acquia.js#L29 Since it doesn't even have that undocumented ability, we should completely remove MariaDB to prevent this type of confusion. Good catch!

**Comment by reynoldsalec** [comment]
@rubenvarela or @uberhacker know you've been active on Acquia if you want to take a look at this...and apologies to @uberhacker, I didn't realize this was the case with Acquia until @spfaffly pointed it out.
